### ISSUE TITLE
No module named 'dlo_hic.utils.align'

### ISSUE THREAD

**Issue by sumu2018** [Nanguage/DLO-HiC-Tools#1]
在正确安装完成后：
测试其他py如：bedpe2pairs.py、build_bedpe.py、noise_reduce.py...
命令如：
python '/home/sun/biosoft/DLO-HiC-Tools/dlo_hic/tools/main_process/bedpe2pairs.py' --help
结果均正常：
Usage: bedpe2pairs.py [OPTIONS] BEDPE PAIRS
  Transform bedpe format file to pairs format, and index it use pairix
  about pairs format:
  https://github.com/4dn-dcic/pairix/blob/master/pairs_format_specification.md
Options:
  --keep / --no-keep  keep non compressed pairs file, if you need create .hic file use --keep option.
  --help              Show this message and exit.

但是运行extract_PET.py时：
python '/home/sun/biosoft/DLO-HiC-Tools/dlo_hic/tools/main_process/extract_PET.py' --help
报错信息：
Traceback (most recent call last):
  File "/home/sun/biosoft/DLO-HiC-Tools/dlo_hic/tools/main_process/extract_PET.py", line 17, in <module>
    from dlo_hic.utils.align import Aligner
ModuleNotFoundError: No module named 'dlo_hic.utils.align'

请问这是什么问题呢？

自检测：
extract_PET.py, line 17
只有运行到这一行时报错：
>>> from dlo_hic.utils.align import Aligner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dlo_hic.utils.align'

麻烦回复，万分感谢！

**Comment by Nanguage** [comment]
试一下：

``` bash
$ dlohic extract_PET --help
```

**Comment by sumu2018** [comment]
thank you !
