### ISSUE TITLE
dlohic interactions_qc计算long-range所占比例

### ISSUE THREAD

**Issue by sumu2018** [Nanguage/DLO-HiC-Tools#2]
您好，在最后一步：
dlohic interactions_qc SRR52.pairs.gz后得到的结果显示：
input pairs file.
interaction quality control:
total:46014
  inter-chr 8955 0.19461
  intra-chr 37059 0.80539
  long-range 31698 0.68888

我对最后一个long-range的占比0.68888有疑问。就是按您的应该是 long-range:31698/total:46014=0.68888,short-range=0.31112.

我理解的是long和short是在intra中来看的，是不是应该： long-range:31698/intra-chr：37059=0.8553,short-range=0.1447？

**Comment by Nanguage** [comment]
Yes, I think you are right. I have corrected it.
