### ISSUE TITLE
question about pair end

### ISSUE THREAD

**Issue by xizhihui** [Nanguage/DLO-HiC-Tools#3]
Hi, thanks for your nice tool.
In your paper, dlo-hic is cost-effective when SE is used. And it seems that this tool is designed only for single end fastq for the reason that it handles the read1 and read2 seperately. How can I use your tool with pair end fastqs? Should I merge read1 and read2 first?

**Comment by Nanguage** [comment]
Actually, R1 is enough for analysis, because the insert-sequense's length is only 80bp, R1 can read through the whole designed structure. In addition, the sequencing quality of R2 is not good as R1 due to the underlying hairpin structure in the reads. So this tool only implemented the SE mode.
